### PR TITLE
Bring back integration test

### PR DESCRIPTION
**Pull request by abhinav**
This brings back the end-to-end integration test
to verify input Markdown against expected HTML.

Some changes from the prior version:

Instead of using goldmark's internal test suite,
we roll our own that stores test data inside a YAML file,
and runs each test case in a separate subtest.
This lets us have better error messages for failures,
and use testify/assert for comparisons -- which prints a diff
in case of failures.

Further, although this verifies almost the exact output,
it does not check whether the generated HTML
contains a trailing newline.
Instead, it always adds one to the end and asserts against that.

Lastly, because managing these files by hand can get annoying,
this adds a '-update-fixtures' flag to `go test`.
Run `go test -update-fixtures` to update the tests.yaml
with the result of rendering.

---

This PR is independent of other open PRs.

Example result of putting the generated HTML into a page:
image

### CODE REVIEW

**Comment by jchenry** [comment]
LGTM

**Comment by jchenry** [comment]
@abhinav thank you for the lift on all of your PRs. Not sure if you have any pikchr or not, so I may inquire as to why you opened them?

**Comment by abhinav** [comment]
> @abhinav thank you for the lift on all of your PRs. Not sure if you have any pikchr or not, so I may inquire as to why you opened them?

Hello, @jchenry!
I do have some pikchr! I discovered it pretty recently, started playing with it, and realized that there are diagrams where I tried to make Mermaid fit, when Pikchr was better suited (where I need more control over layout, e.g.). I've since switched them over.

But that also led me down a rabbit hole, and eventually I tried to answer "can I integrate this into a hypothetical goldmark-based static site generator," which is how I ran into your project. (I was delighted to discover that you took inspiration from goldmark-mermaid for project setup. Thanks for the call out!)

So... yeah, that's how I ended up making the PRs. 😄

**Comment by jchenry** [comment]
@abhinav well thank you again :-)

**Pull request merged**
